---
title: "La criminalité en France métropolitaine en 2016"
author: "Floch Elisa, Goutard Amelie et Marmion Violette"
date: "21/03/2022"
output: 
  rmdformats::robobook:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    code_folding: show
  html_document:
    code_folding: show
    theme: united
    highlight: tango
    toc: true
    toc_float: true
---

<style>body {text-align: justify}</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# 1. Présentation du sujet 

L’objectif de cette application (disponible [ici](https://data.world/notgibs/rolling-stones-top-500-albums)) est de présenter à l‘utilisateur une interface qui lui permettra d’identifier et d’analyser le taux de criminalité en France métropolitaine en 2016. 

Un modèle de données de panel a été estimé en utilisant les données des départements français. Pour construire notre modèle, nous avons considéré plusieurs facteurs sociaux qui pourraient contribuer à l’évolution du phénomène.

L’analyse se concentrera sur les déterminants de tous les délits recensés en France métropolitaine en 2016. Prenons la définition de la criminalité donnée par l’INSEE, les crimes et délits constatés en France sont des faits bruts portés pour la première fois à la connaissance des services de police et de gendarmerie. Sont exclus des statistiques de la criminalité constatée, l'ensemble des contraventions ainsi que les délits relatifs à la circulation routière, les actes de police administrative et les infractions relevées par d'autres administrations (douanes, services fiscaux et répression des fraudes, inspection du travail...).

# 2. Présentation des données

## 2.1 Importation des données

Dans un premier temps, nous avons importé les différentes bases de données. La base principale porte sur les délits en France en 2016. Nous avons supprimé les lignes vides intitulées « index non utilisés ». Ensuite, nous avons attribué comme nom de ligne, le nom des différents délits. Puis, nous avons transposé la base car nous souhaitions avoir les délits en colonne et nous avons ajouté une colonne comprenant les 96 départements de France métropolitaine. Suite à cela, nous avons importé les bases contenant les différents indicateurs. Les bases incluant les données sur la population, le taux de pauvreté et l’indice de Gini ont été importées facilement. Nous avons seulement dû renommer la variable département pour que les jointures se fassent naturellement. En revanche, nous avons dû modifier la base diplôme en regroupant certaines colonnes. Les variables représentant le niveau de diplôme étaient ordonnées par sexe et par tranche d’âge, nous avons donc regroupé les colonnes par type car nous nous intéressons à la population générale. De plus, les données étant triées par commune, nous avons effectué un nouveau regroupement pour les avoir par département. Enfin, nous avons ajouté la population totale pour chaque département afin de calculer la part de personnes diplômées et la part de personnes non-diplômées. Pour finir, la base sur le taux de chômage contenait des données allant de 1982 à 2019, nous avons seulement conservé les données de 2016. Les données étant présentées par trimestre, nous avons décidé d’en faire la moyenne pour avoir un taux de chômage annuel moyen pour chaque département. Nous avons décidé d'exclure le salaire médian de notre analyse puisque celui-ci diffère en fonction du département (ex : vie qui coute plus chère à Paris donc salaires plus élevés) alors que l'indice de gini mesure l'inégalité des revenus. 

Dans un second temps, nous avons vérifié qu’il n’y avait pas de données manquantes ou aberrantes. Une fois la révision faite, nous avons pu créer différentes bases. Il existe différents groupes de délits tels que les homicides, les violences sexuelles, les coups et blessures volontaires, les vols avec armes, etc.

Ensuite, nous avons ajouté les marges sur la base complète : une ligne avec le nombre total de chaque délit ainsi qu’une colonne avec le nombre total de délits pour chaque département.

Dans un dernier temps, nous avons fait la jointure des bases. Nous avons joint la base aux données concernant la population, la pauvreté, le diplôme, l’indice de Gini et le taux de chômage pour chaque département.

