---
title: "La criminalité en France métropolitaine en 2016"
author: "Floch Elisa, Goutard Amelie et Marmion Violette"
date: "21/03/2022"
output: 
  rmdformats::robobook:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    code_folding: show
  html_document:
    code_folding: show
    theme: united
    highlight: tango
    toc: true
    toc_float: true
---

# 1. Présentation du sujet 

L’objectif de cette application est de présenter à l‘utilisateur une interface qui lui permette d’identifier et d’analyser le taux de criminalité en France métropolitaine en 2016. 

Un modèle de données de panel a été estimé en utilisant les données des départements français. Pour construire notre modèle, nous avons considéré plusieurs facteurs sociaux qui pourraient contribuer à l’évolution du phénomène.

L’analyse se concentrera sur les déterminants de tous les délits recensés en France métropolitaine en 2016. Prenons la définition de la criminalité donnée par l’INSEE, les crimes et délits constatés en France sont des faits bruts portés pour la première fois à la connaissance des services de police et de gendarmerie. Sont exclus des statistiques de la criminalité constatée, l'ensemble des contraventions ainsi que les délits relatifs à la circulation routière, les actes de police administrative et les infractions relevées par d'autres administrations (douanes, services fiscaux et répression des fraudes, inspection du travail...).

# 2. Présentation des données

Voici le dictionnaire des données : 

Champs  | Correspondance | Occurences | Type de données |
------------- | ------------- | ------------- | ------------- |
Département  | Numéro de département (France métropolitaine) |{0, ...2A,2B, ..., 95} | Qualitative |
Total_delits | Nombre de délits violents par département en 2016 | {530, ..., 57 902} | Quantitative discrète |
Salaire_median | Salaire médian par département en 2016 | {22 272, ...} | Quantitative continue |
Tx_pauvrete_seuil60 | Taux de pauvreté au seuil de 60% (en%) par département en 2016 |{10.7, 18.9, ...} | Quantitative continue |
Taux_chomage_moyen | Taux de chômage (en%) par département en 2016 | {7.35, 13.7, ...} | Quantitative continue |
Content Cell  | Content Cell  | Content Cell  | Content Cell  |
Content Cell  | Content Cell  | Content Cell  | Content Cell  |
Content Cell  | Content Cell  | Content Cell  | Content Cell  |

# 3. Statistiques descriptives

## 3.1 Statistiques univariées

## 3.2 Statistiques bivariées

# 4. Modélisation économétrique
